use std::collections::{HashMap, HashSet};

use regex::Regex;

use crate::util::new_regex_map;

#[derive(Clone)]
pub struct Trigger {
    pub signal: &'static str,
    pub source: &'static str,
}

pub struct Triggers {
    map: regex_map::RegexMap<Vec<Trigger>>,
}

impl Triggers {
    pub fn new() -> Self {
        /// Regexmap where the key is mcu_name:peripheral and the value is the trigger list.
        #[rustfmt::skip]
        const PERIPHERAL_TRIGGER_RULES: &[(&str, &'static [Trigger])] = &[
            (r"^STM32F0.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F100.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F10[13].[CDEFG]:ADC(1|2)", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_CH1"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CH2"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CH3"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM2_CH2"},
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG5", source: "TIM4_CH4"},
                Trigger {signal: "ADC_EXT_TRG6", source: "EXTI11_TRG"},
                Trigger {signal: "ADC_EXT_TRG6", source: "TIM8_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CH4"},
                Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG3", source: "TIM2_CH1"},
                Trigger {signal: "ADC_JEXT_TRG4", source: "TIM3_CH4"},
                Trigger {signal: "ADC_JEXT_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG6", source: "EXTI15_TRG"},
                Trigger {signal: "ADC_JEXT_TRG6", source: "TIM8_CH4"},
            ]),
            (r"^STM32F10[1-357].*:ADC(1|2)", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_CH1"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CH2"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CH3"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM2_CH2"},
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG5", source: "TIM4_CH4"},
                Trigger {signal: "ADC_EXT_TRG6", source: "EXTI11_TRG"},
                Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CH4"},
                Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG3", source: "TIM2_CH1"},
                Trigger {signal: "ADC_JEXT_TRG4", source: "TIM3_CH4"},
                Trigger {signal: "ADC_JEXT_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG6", source: "EXTI15_TRG"},
            ]),
            (r"^STM32F10[13].[CDEFG]:ADC3", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM3_CH1"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM2_CH3"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CH3"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM8_CH1"},
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM8_TRGO"},
                Trigger {signal: "ADC_EXT_TRG5", source: "TIM5_CH1"},
                Trigger {signal: "ADC_EXT_TRG6", source: "TIM5_CH3"},
                Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CH4"},
                Trigger {signal: "ADC_JEXT_TRG2", source: "TIM4_CH3"},
                Trigger {signal: "ADC_JEXT_TRG3", source: "TIM8_CH2"},
                Trigger {signal: "ADC_JEXT_TRG4", source: "TIM8_CH4"},
                Trigger {signal: "ADC_JEXT_TRG5", source: "TIM5_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG6", source: "TIM5_CH4"},
            ]),
            (r"^STM32F101.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F103.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F105.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F107.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F1.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F410.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F4.*:ADC.*", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_CH1" },
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CH2" },
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CH3" },
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM2_CH2" },
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM2_CH3" },
                Trigger {signal: "ADC_EXT_TRG5", source: "TIM2_CH4" },
                Trigger {signal: "ADC_EXT_TRG6", source: "TIM2_TRGO" },
                Trigger {signal: "ADC_EXT_TRG7", source: "TIM3_CH1" },
                Trigger {signal: "ADC_EXT_TRG8", source: "TIM3_TRGO" },
                Trigger {signal: "ADC_EXT_TRG9", source: "TIM4_CH4" },
                Trigger {signal: "ADC_EXT_TRG10", source: "TIM5_CH1" },
                Trigger {signal: "ADC_EXT_TRG11", source: "TIM5_CH2" },
                Trigger {signal: "ADC_EXT_TRG12", source: "TIM5_CH3" },
                Trigger {signal: "ADC_EXT_TRG13", source: "TIM8_CH1" },
                Trigger {signal: "ADC_EXT_TRG14", source: "TIM8_TRGO" },
                Trigger {signal: "ADC_EXT_TRG15", source: "EXTI11_TRG" },
                Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_CH4" },
                Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_CH1" },
                Trigger {signal: "ADC_JEXT_TRG3", source: "TIM2_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG4", source: "TIM3_CH2" },
                Trigger {signal: "ADC_JEXT_TRG5", source: "TIM3_CH4" },
                Trigger {signal: "ADC_JEXT_TRG6", source: "TIM4_CH1" },
                Trigger {signal: "ADC_JEXT_TRG7", source: "TIM4_CH2" },
                Trigger {signal: "ADC_JEXT_TRG8", source: "TIM4_CH3" },
                Trigger {signal: "ADC_JEXT_TRG9", source: "TIM4_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG10", source: "TIM5_CH4" },
                Trigger {signal: "ADC_JEXT_TRG11", source: "TIM5_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG12", source: "TIM8_CH2" },
                Trigger {signal: "ADC_JEXT_TRG13", source: "TIM8_CH3" },
                Trigger {signal: "ADC_JEXT_TRG14", source: "TIM8_CH4" },
                Trigger {signal: "ADC_JEXT_TRG15", source: "EXTI15_TRG" },
            ]),
            (r"^STM32L4(5|6).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32(F2|F4|F7|L4).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F3(01|02|18).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F3(03|28|58|98).*:DAC1", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"}, // defaults to TIM8 but can be remapped to TIM3 with DAC_TRIG_RMP in SYSCFG_CFGR1
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F3(03|28|58|98).*:DAC2", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F37(3|8).*:DAC1", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F37(3|8).*:DAC2", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM18_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "EXTI9_TRG"},
            ]),
            (r"^STM32F334.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "HRTIM_DAC_TRG1"}, // Can be remapped to HRTIM_DACTRG1 using DAC1_TRIG3_RMP in SYSCFG_CFGR3.
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "HRTIM_DAC_TRG2"}, // Requires DAC_TRIG5_RMP set in SYSCFG_CFGR3.
            ]),
            (r"^STM32L0.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM3CH3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM21_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32L0.*:TIM2", &[
                Trigger {signal: "TIMX_TI4_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI4_IN2", source: "COMP2_OUT"},
            ]),
            (r"^STM32L0.*:TIM21", &[
                Trigger {signal: "TIMX_TI1_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI1_IN2", source: "COMP2_OUT"},
            ]),
            (r"^STM32L0.*:TIM22", &[
                Trigger {signal: "TIMX_TI1_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI1_IN2", source: "COMP2_OUT"},
            ]),
            (r"^STM32L1.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM9_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            ]),
            (r"^STM32H7(2|3).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
                Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
                Trigger {signal: "DAC_CHX_TRG14", source: "TIM23_TRGO"},
                Trigger {signal: "DAC_CHX_TRG15", source: "TIM24_TRGO"},
            ]),
            (r"^STM32H7(A|B).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
                Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
                Trigger {signal: "DAC_CHX_TRG14", source: "LPTIM3_TRGO"},
            ]),
            (r"^STM32H7.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
                Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            ]),
            (r"^STM32(U5|U3).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            ]),
            (r"^STM32(L4|L5).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            ]),
            (r"^STM32H503.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            ]),
            (r"^STM32H5(6|7).*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
                Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            ]),
            (r"^STM32H5.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            ]),
            (r"^STM32G0.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            ]),
            (r"^STM32G0.*:ADC.*", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CC4"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM15_TRGO"},
                Trigger {signal: "ADC_EXT_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "ADC_EXT_TRG6", source: "TIM4_TRGO"},
                Trigger {signal: "ADC_EXT_TRG7", source: "EXTI11_TRG"},
            ]),
            (r"^STM32C0(91|92).*:ADC.*", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CC4"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM15_TRGO"},
                Trigger {signal: "ADC_EXT_TRG7", source: "EXTI11_TRG"},
            ]),
            (r"^STM32C0(51|71).*:ADC.*", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CC4"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG7", source: "EXTI11_TRG"},
            ]),
            (r"^STM32C0(11|31).*:ADC.*", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CC4"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG7", source: "EXTI11_TRG"},
            ]),
            (r"^STM32U0.*:TIM1", &[
                Trigger {signal: "TIMX_TI1_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI2_IN1", source: "COMP2_OUT"},
            ]),
            (r"^STM32U0.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG14", source: "EXTI9_TRG"},
            ]),
            (r"^STM32H5.*:ADC(1|2|3)", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_CC1"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CC2"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CC3"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM2_CC2"},
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG5", source: "TIM4_CC4"},
                Trigger {signal: "ADC_EXT_TRG6", source: "EXTI11_TRG"},
                Trigger {signal: "ADC_EXT_TRG7", source: "TIM8_TRGO"},
                Trigger {signal: "ADC_EXT_TRG8", source: "TIM8_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG9", source: "TIM1_TRGO"},
                Trigger {signal: "ADC_EXT_TRG10", source: "TIM1_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG11", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_EXT_TRG12", source: "TIM4_TRGO"},
                Trigger {signal: "ADC_EXT_TRG13", source: "TIM6_TRGO"},
                Trigger {signal: "ADC_EXT_TRG14", source: "TIM15_TRGO"},
                Trigger {signal: "ADC_EXT_TRG15", source: "TIM3_CC4"},
                Trigger {signal: "ADC_EXT_TRG16", source: "EXTI15_TRG"},
                Trigger {signal: "ADC_EXT_TRG18", source: "LPTIM1_CH1"},
                Trigger {signal: "ADC_EXT_TRG19", source: "LPTIM2_CH1"},
                Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CC4" },
                Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG3", source: "TIM2_CC1" },
                Trigger {signal: "ADC_JEXT_TRG4", source: "TIM3_CC4" },
                Trigger {signal: "ADC_JEXT_TRG5", source: "TIM4_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG6", source: "EXTI15_TRG" },
                Trigger {signal: "ADC_JEXT_TRG7", source: "TIM8_CC4" },
                Trigger {signal: "ADC_JEXT_TRG8", source: "TIM1_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG9", source: "TIM8_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG10", source: "TIM8_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG11", source: "TIM3_CC3" },
                Trigger {signal: "ADC_JEXT_TRG12", source: "TIM3_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG13", source: "TIM3_CC1" },
                Trigger {signal: "ADC_JEXT_TRG14", source: "TIM6_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG15", source: "TIM15_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG18", source: "LPTIM1_CH1"},
                Trigger {signal: "ADC_JEXT_TRG19", source: "LPTIM2_CH1"},
            ]),
            (r"^STM32G4.*:ADC(1|2)", &[
                Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_CC1"},
                Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CC2"},
                Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CC3"},
                Trigger {signal: "ADC_EXT_TRG3", source: "TIM2_CC2"},
                Trigger {signal: "ADC_EXT_TRG4", source: "TIM3_TRGO"},
                Trigger {signal: "ADC_EXT_TRG5", source: "TIM4_CC4"},
                Trigger {signal: "ADC_EXT_TRG6", source: "EXTI11_TRG"},
                Trigger {signal: "ADC_EXT_TRG7", source: "TIM8_TRGO"},
                Trigger {signal: "ADC_EXT_TRG8", source: "TIM8_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG9", source: "TIM1_TRGO"},
                Trigger {signal: "ADC_EXT_TRG10", source: "TIM1_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG11", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_EXT_TRG12", source: "TIM4_TRGO"},
                Trigger {signal: "ADC_EXT_TRG13", source: "TIM6_TRGO"},
                Trigger {signal: "ADC_EXT_TRG14", source: "TIM15_TRGO"},
                Trigger {signal: "ADC_EXT_TRG15", source: "TIM3_CC4"},
                Trigger {signal: "ADC_EXT_TRG16", source: "TIM20_TRGO"},
                Trigger {signal: "ADC_EXT_TRG17", source: "TIM20_TRGO2"},
                Trigger {signal: "ADC_EXT_TRG18", source: "TIM20_CC1"},
                Trigger {signal: "ADC_EXT_TRG19", source: "TIM20_CC2"},
                Trigger {signal: "ADC_EXT_TRG20", source: "TIM20_CC3"},
                Trigger {signal: "ADC_EXT_TRG21", source: "HRTIM_ADC_TRG1"},
                Trigger {signal: "ADC_EXT_TRG22", source: "HRTIM_ADC_TRG3"},
                Trigger {signal: "ADC_EXT_TRG23", source: "HRTIM_ADC_TRG5"},
                Trigger {signal: "ADC_EXT_TRG24", source: "HRTIM_ADC_TRG6"},
                Trigger {signal: "ADC_EXT_TRG25", source: "HRTIM_ADC_TRG7"},
                Trigger {signal: "ADC_EXT_TRG26", source: "HRTIM_ADC_TRG8"},
                Trigger {signal: "ADC_EXT_TRG27", source: "HRTIM_ADC_TRG9"},
                Trigger {signal: "ADC_EXT_TRG28", source: "HRTIM_ADC_TRG10"},
                Trigger {signal: "ADC_EXT_TRG29", source: "LPTIMOUT"},
                Trigger {signal: "ADC_EXT_TRG30", source: "TIM7_TRGO"},
                Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CC4" },
                Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG3", source: "TIM2_CC1" },
                Trigger {signal: "ADC_JEXT_TRG4", source: "TIM3_CC4" },
                Trigger {signal: "ADC_JEXT_TRG5", source: "TIM4_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG6", source: "EXTI15_TRG" },
                Trigger {signal: "ADC_JEXT_TRG7", source: "TIM8_CC4" },
                Trigger {signal: "ADC_JEXT_TRG8", source: "TIM1_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG9", source: "TIM8_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG10", source: "TIM8_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG11", source: "TIM3_CC3" },
                Trigger {signal: "ADC_JEXT_TRG12", source: "TIM3_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG13", source: "TIM3_CC1" },
                Trigger {signal: "ADC_JEXT_TRG14", source: "TIM6_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG15", source: "TIM15_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG16", source: "TIM20_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG17", source: "TIM20_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG18", source: "TIM20_CC4" },
                Trigger {signal: "ADC_JEXT_TRG19", source: "HRTIM_ADC_TRG2" },
                Trigger {signal: "ADC_JEXT_TRG20", source: "HRTIM_ADC_TRG4" },
                Trigger {signal: "ADC_JEXT_TRG21", source: "HRTIM_ADC_TRG5" },
                Trigger {signal: "ADC_JEXT_TRG22", source: "HRTIM_ADC_TRG6" },
                Trigger {signal: "ADC_JEXT_TRG23", source: "HRTIM_ADC_TRG7" },
                Trigger {signal: "ADC_JEXT_TRG24", source: "HRTIM_ADC_TRG8" },
                Trigger {signal: "ADC_JEXT_TRG25", source: "HRTIM_ADC_TRG9" },
                Trigger {signal: "ADC_JEXT_TRG26", source: "HRTIM_ADC_TRG10" },
                Trigger {signal: "ADC_JEXT_TRG27", source: "TIM16_CC1" },
                Trigger {signal: "ADC_JEXT_TRG29", source: "LPTIMOUT" },
                Trigger {signal: "ADC_JEXT_TRG30", source: "TIM7_TRGO" },
            ]),
            (r"^STM32G4.*:ADC(3|4|5)", &[
                Trigger {signal: "ADC_EXT_TRG0", source:  "TIM3_CC1" },
                Trigger {signal: "ADC_EXT_TRG1", source:  "TIM2_CC3" },
                Trigger {signal: "ADC_EXT_TRG2", source:  "TIM1_CC3" },
                Trigger {signal: "ADC_EXT_TRG3", source:  "TIM8_CC1" },
                Trigger {signal: "ADC_EXT_TRG4", source:  "TIM3_TRGO" },
                Trigger {signal: "ADC_EXT_TRG5", source:  "EXTI2_TRG" },
                Trigger {signal: "ADC_EXT_TRG6", source:  "TIM4_CC1" },
                Trigger {signal: "ADC_EXT_TRG7", source:  "TIM8_TRGO" },
                Trigger {signal: "ADC_EXT_TRG8", source:  "TIM8_TRGO2" },
                Trigger {signal: "ADC_EXT_TRG9", source:  "TIM1_TRGO" },
                Trigger {signal: "ADC_EXT_TRG10", source:  "TIM1_TRGO2" },
                Trigger {signal: "ADC_EXT_TRG11", source:  "TIM2_TRGO" },
                Trigger {signal: "ADC_EXT_TRG12", source:  "TIM4_TRGO" },
                Trigger {signal: "ADC_EXT_TRG13", source:  "TIM6_TRGO" },
                Trigger {signal: "ADC_EXT_TRG14", source:  "TIM15_TRGO" },
                Trigger {signal: "ADC_EXT_TRG15", source:  "TIM2_CC1" },
                Trigger {signal: "ADC_EXT_TRG16", source:  "TIM20_TRGO" },
                Trigger {signal: "ADC_EXT_TRG17", source:  "TIM20_TRGO2" },
                Trigger {signal: "ADC_EXT_TRG18", source:  "TIM20_CC1" },
                Trigger {signal: "ADC_EXT_TRG19", source:  "HRTIM_ADC_TRG2" },
                Trigger {signal: "ADC_EXT_TRG20", source:  "HRTIM_ADC_TRG4" },
                Trigger {signal: "ADC_EXT_TRG21", source:  "HRTIM_ADC_TRG1" },
                Trigger {signal: "ADC_EXT_TRG22", source:  "HRTIM_ADC_TRG3" },
                Trigger {signal: "ADC_EXT_TRG23", source:  "HRTIM_ADC_TRG5" },
                Trigger {signal: "ADC_EXT_TRG24", source:  "HRTIM_ADC_TRG6" },
                Trigger {signal: "ADC_EXT_TRG25", source:  "HRTIM_ADC_TRG7" },
                Trigger {signal: "ADC_EXT_TRG26", source:  "HRTIM_ADC_TRG8" },
                Trigger {signal: "ADC_EXT_TRG27", source:  "HRTIM_ADC_TRG9" },
                Trigger {signal: "ADC_EXT_TRG28", source:  "HRTIM_ADC_TRG10" },
                Trigger {signal: "ADC_EXT_TRG29", source:  "LPTIMOUT" },
                Trigger {signal: "ADC_EXT_TRG30", source:  "TIM7_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CC4" },
                Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG3", source: "TIM8_CC2" },
                Trigger {signal: "ADC_JEXT_TRG4", source: "TIM4_CC3" },
                Trigger {signal: "ADC_JEXT_TRG5", source: "TIM4_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG6", source: "TIM4_CC4" },
                Trigger {signal: "ADC_JEXT_TRG7", source: "TIM8_CC4" },
                Trigger {signal: "ADC_JEXT_TRG8", source: "TIM1_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG9", source: "TIM8_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG10", source: "TIM8_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG11", source: "TIM1_CC3" },
                Trigger {signal: "ADC_JEXT_TRG12", source: "TIM3_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG13", source: "EXTI3_TRG" },
                Trigger {signal: "ADC_JEXT_TRG14", source: "TIM6_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG15", source: "TIM15_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG16", source: "TIM20_TRGO" },
                Trigger {signal: "ADC_JEXT_TRG17", source: "TIM20_TRGO2" },
                Trigger {signal: "ADC_JEXT_TRG18", source: "TIM20_CC2" },
                Trigger {signal: "ADC_JEXT_TRG19", source: "HRTIM_ADC_TRG2" },
                Trigger {signal: "ADC_JEXT_TRG20", source: "HRTIM_ADC_TRG4" },
                Trigger {signal: "ADC_JEXT_TRG21", source: "HRTIM_ADC_TRG5" },
                Trigger {signal: "ADC_JEXT_TRG22", source: "HRTIM_ADC_TRG6" },
                Trigger {signal: "ADC_JEXT_TRG23", source: "HRTIM_ADC_TRG7" },
                Trigger {signal: "ADC_JEXT_TRG24", source: "HRTIM_ADC_TRG8" },
                Trigger {signal: "ADC_JEXT_TRG25", source: "HRTIM_ADC_TRG9" },
                Trigger {signal: "ADC_JEXT_TRG26", source: "HRTIM_ADC_TRG10" },
                Trigger {signal: "ADC_JEXT_TRG27", source: "HRTIM_ADC_TRG1" },
                Trigger {signal: "ADC_JEXT_TRG28", source: "HRTIM_ADC_TRG3" },
                Trigger {signal: "ADC_JEXT_TRG29", source: "LPTIMOUT" },
                Trigger {signal: "ADC_JEXT_TRG30", source: "TIM7_TRGO" },
            ]),
            (r"^STM32G4.*:DAC(1|4)", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG1"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
                Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
                Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
                Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
                Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
                Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
                Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
                Trigger {signal: "DAC_INC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG6", source: "EXTI10_TRG"},
                Trigger {signal: "DAC_INC_CHX_TRG7", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG8", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG9", source: "HRTIM_DAC_STEP_TRG1"},
                Trigger {signal: "DAC_INC_CHX_TRG10", source: "HRTIM_DAC_STEP_TRG2"},
                Trigger {signal: "DAC_INC_CHX_TRG11", source: "HRTIM_DAC_STEP_TRG3"},
                Trigger {signal: "DAC_INC_CHX_TRG12", source: "HRTIM_DAC_STEP_TRG4"},
                Trigger {signal: "DAC_INC_CHX_TRG13", source: "HRTIM_DAC_STEP_TRG5"},
                Trigger {signal: "DAC_INC_CHX_TRG14", source: "HRTIM_DAC_STEP_TRG6"},
            ]),
            (r"^STM32G4.*:DAC2", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG2"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
                Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
                Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
                Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
                Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
                Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
                Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
                Trigger {signal: "DAC_INC_CHX_TRG1", source: "TIM8_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG6", source: "EXTI10_TRG"},
                Trigger {signal: "DAC_INC_CHX_TRG7", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG8", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG9", source: "HRTIM_DAC_STEP_TRG1"},
                Trigger {signal: "DAC_INC_CHX_TRG10", source: "HRTIM_DAC_STEP_TRG2"},
                Trigger {signal: "DAC_INC_CHX_TRG11", source: "HRTIM_DAC_STEP_TRG3"},
                Trigger {signal: "DAC_INC_CHX_TRG12", source: "HRTIM_DAC_STEP_TRG4"},
                Trigger {signal: "DAC_INC_CHX_TRG13", source: "HRTIM_DAC_STEP_TRG5"},
                Trigger {signal: "DAC_INC_CHX_TRG14", source: "HRTIM_DAC_STEP_TRG6"},
            ]),
            (r"^STM32G4.*:DAC3", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG3"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
                Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
                Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
                Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
                Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
                Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
                Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
                Trigger {signal: "DAC_INC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG2", source: "TIM7_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG3", source: "TIM15_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG4", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG5", source: "TIM4_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG6", source: "EXTI10_TRG"},
                Trigger {signal: "DAC_INC_CHX_TRG7", source: "TIM6_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG8", source: "TIM3_TRGO"},
                Trigger {signal: "DAC_INC_CHX_TRG9", source: "HRTIM_DAC_STEP_TRG1"},
                Trigger {signal: "DAC_INC_CHX_TRG10", source: "HRTIM_DAC_STEP_TRG2"},
                Trigger {signal: "DAC_INC_CHX_TRG11", source: "HRTIM_DAC_STEP_TRG3"},
                Trigger {signal: "DAC_INC_CHX_TRG12", source: "HRTIM_DAC_STEP_TRG4"},
                Trigger {signal: "DAC_INC_CHX_TRG13", source: "HRTIM_DAC_STEP_TRG5"},
                Trigger {signal: "DAC_INC_CHX_TRG14", source: "HRTIM_DAC_STEP_TRG6"},
            ]),
            (r"^STM32G4.*:TIM1", &[
                Trigger {signal: "TIMX_TI1_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI1_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_TI1_IN3", source: "COMP3_OUT"},
                Trigger {signal: "TIMX_TI1_IN4", source: "COMP4_OUT"},
            ]),
            (r"^STM32WL.*:TIM1", &[
                Trigger {signal: "TIMX_TI1_IN1", source: "COMP1_OUT"},
            ]),
            (r"^STM32WL.*:TIM2", &[
                Trigger {signal: "TIMX_TI4_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI4_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_TI4_IN3", source: "COMP1_OUT_OR_COMP2_OUT"},
            ]),
            (r"^STM32WBA5[45].*:TIM1", &[
                Trigger {signal: "TIMX_TI1_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI1_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_ITR_IN1", source: "TIM2_TRGO"},
                Trigger {signal: "TIMX_ITR_IN2", source: "TIM3_TRGO"},
                Trigger {signal: "TIMX_ITR_IN7", source: "TIM16_OC1"},
                Trigger {signal: "TIMX_ITR_IN8", source: "TIM17_OC1"},
                Trigger {signal: "TIMX_ETR_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_ETR_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_ETR_IN11", source: "ADC4_AWD1"},
                Trigger {signal: "TIMX_ETR_IN12", source: "ADC4_AWD2"},
                Trigger {signal: "TIMX_ETR_IN13", source: "ADC4_AWD3"},
                Trigger {signal: "TIMX_BRK_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_BRK_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_BRK2_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_BRK2_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_SYS_BRK_IN0", source: "CORTEX_M33_LOCKUP"},
                Trigger {signal: "TIMX_SYS_BRK_IN1", source: "PVD"},
                Trigger {signal: "TIMX_SYS_BRK_IN2", source: "SRAM_PARITY_ERROR"},
                Trigger {signal: "TIMX_SYS_BRK_IN3", source: "FLASH_ECC_ERROR"},
                Trigger {signal: "TIMX_SYS_BRK_IN4", source: "HSE2_HSECSS"},
                Trigger {signal: "TIMX_OCREF_CLR_IN0", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_OCREF_CLR_IN1", source: "COMP2_OUT"},
            ]),
            (r"^STM32WBA6[235].*:TIM1", &[
                Trigger {signal: "TIMX_TI1_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_TI1_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_ITR_IN1", source: "TIM2_TRGO"},
                Trigger {signal: "TIMX_ITR_IN2", source: "TIM3_TRGO"},
                Trigger {signal: "TIMX_ETR_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_ETR_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_ETR_IN11", source: "ADC4_AWD1"},
                Trigger {signal: "TIMX_ETR_IN12", source: "ADC4_AWD2"},
                Trigger {signal: "TIMX_ETR_IN13", source: "ADC4_AWD3"},
                Trigger {signal: "TIMX_BRK_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_BRK_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_BRK2_IN1", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_BRK2_IN2", source: "COMP2_OUT"},
                Trigger {signal: "TIMX_SYS_BRK_IN0", source: "CORTEX_M33_LOCKUP"},
                Trigger {signal: "TIMX_SYS_BRK_IN1", source: "PVD"},
                Trigger {signal: "TIMX_SYS_BRK_IN2", source: "SRAM_PARITY_ERROR"},
                Trigger {signal: "TIMX_SYS_BRK_IN3", source: "FLASH_ECC_ERROR"},
                Trigger {signal: "TIMX_SYS_BRK_IN4", source: "HSE32_HSECSS"},
                Trigger {signal: "TIMX_OCREF_CLR_IN0", source: "COMP1_OUT"},
                Trigger {signal: "TIMX_OCREF_CLR_IN1", source: "COMP2_OUT"},
            ]),
            (r"^STM32WBA6[245].*:TIM1", &[
                Trigger {signal: "TIMX_ITR_IN3", source: "TIM4_TRGO"},
                Trigger {signal: "TIMX_ITR_IN7", source: "TIM16_OC1"},
                Trigger {signal: "TIMX_ITR_IN8", source: "TIM17_OC1"},
            ]),
            (r"^STM32WBA6[235].*:LPTIM1", &[
                Trigger {signal: "LPTIM_EXT_TRG0", source: "LPTIM1_ETR"},
                Trigger {signal: "LPTIM_EXT_TRG1", source: "RTC_ALRA_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG2", source: "RTC_ALRB_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG3", source: "TAMP_TRG1"},
                Trigger {signal: "LPTIM_EXT_TRG4", source: "TAMP_TRG2"},
                Trigger {signal: "LPTIM_EXT_TRG6", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_EXT_TRG7", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IN1_MUX0", source: "LPTIM1_IN1"},
                Trigger {signal: "LPTIM_IN1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IN2_MUX0", source: "LPTIM1_IN2"},
                Trigger {signal: "LPTIM_IN2_MUX1", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX0", source: "LPTIM1_CH1"},
                Trigger {signal: "LPTIM_IC1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX2", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC2_MUX0", source: "LPTIM1_CH2"},
                Trigger {signal: "LPTIM_IC2_MUX1", source: "LSI"},
                Trigger {signal: "LPTIM_IC2_MUX2", source: "LSE"},
            ]),
            (r"^STM32WBA6[235].*:LPTIM2", &[
                Trigger {signal: "LPTIM_EXT_TRG0", source: "LPTIM2_ETR"},
                Trigger {signal: "LPTIM_EXT_TRG1", source: "RTC_ALRA_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG2", source: "RTC_ALRB_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG3", source: "TAMP_TRG1"},
                Trigger {signal: "LPTIM_EXT_TRG4", source: "GPDMA_CH0_TC"},
                Trigger {signal: "LPTIM_EXT_TRG5", source: "GPDMA_CH1_TC"},
                Trigger {signal: "LPTIM_EXT_TRG6", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_EXT_TRG7", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IN1_MUX0", source: "LPTIM2_IN1"},
                Trigger {signal: "LPTIM_IN1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IN2_MUX0", source: "LPTIM2_IN2"},
                Trigger {signal: "LPTIM_IN2_MUX1", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX0", source: "LPTIM2_CH1"},
                Trigger {signal: "LPTIM_IC1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX2", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC2_MUX0", source: "LPTIM2_CH2"},
                Trigger {signal: "LPTIM_IC2_MUX1", source: "HSI16_DIV256"},
            ]),
            (r"^STM32WBA6[235].*:SPI[12]", &[
                Trigger {signal: "SPI_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "SPI_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "SPI_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "SPI_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "SPI_TRG4", source: "EXTI4_TRG"},
                Trigger {signal: "SPI_TRG5", source: "EXTI9_TRG"},
                Trigger {signal: "SPI_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "SPI_TRG7", source: "LPTIM2_CH1"},
                Trigger {signal: "SPI_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "SPI_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "SPI_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "SPI_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA6[235].*:SPI3", &[
                Trigger {signal: "SPI_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "SPI_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "SPI_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "SPI_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "SPI_TRG4", source: "EXTI4_TRG"},
                Trigger {signal: "SPI_TRG5", source: "EXTI8_TRG"},
                Trigger {signal: "SPI_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "SPI_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "SPI_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "SPI_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA6[235].*:USART[12]", &[
                Trigger {signal: "USART_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "USART_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "USART_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "USART_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "USART_TRG4", source: "EXTI6_TRG"},
                Trigger {signal: "USART_TRG5", source: "EXTI9_TRG"},
                Trigger {signal: "USART_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "USART_TRG7", source: "LPTIM2_CH1"},
                Trigger {signal: "USART_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "USART_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "USART_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "USART_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA5[45].*:LPTIM1", &[
                Trigger {signal: "LPTIM_EXT_TRG0", source: "LPTIM1_ETR"},
                Trigger {signal: "LPTIM_EXT_TRG1", source: "RTC_ALRA_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG2", source: "RTC_ALRB_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG3", source: "TAMP_TRG1"},
                Trigger {signal: "LPTIM_EXT_TRG4", source: "TAMP_TRG2"},
                Trigger {signal: "LPTIM_EXT_TRG6", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_EXT_TRG7", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IN1_MUX0", source: "LPTIM1_IN1"},
                Trigger {signal: "LPTIM_IN1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IN2_MUX0", source: "LPTIM1_IN2"},
                Trigger {signal: "LPTIM_IN2_MUX1", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX0", source: "LPTIM1_CH1"},
                Trigger {signal: "LPTIM_IC1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX2", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC2_MUX0", source: "LPTIM1_CH2"},
                Trigger {signal: "LPTIM_IC2_MUX1", source: "LSI"},
                Trigger {signal: "LPTIM_IC2_MUX2", source: "LSE"},
            ]),
            (r"^STM32WBA5[45].*:LPTIM2", &[
                Trigger {signal: "LPTIM_EXT_TRG0", source: "LPTIM2_ETR"},
                Trigger {signal: "LPTIM_EXT_TRG1", source: "RTC_ALRA_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG2", source: "RTC_ALRB_TRG"},
                Trigger {signal: "LPTIM_EXT_TRG3", source: "TAMP_TRG1"},
                Trigger {signal: "LPTIM_EXT_TRG4", source: "GPDMA_CH0_TC"},
                Trigger {signal: "LPTIM_EXT_TRG5", source: "GPDMA_CH4_TC"},
                Trigger {signal: "LPTIM_EXT_TRG6", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_EXT_TRG7", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IN1_MUX0", source: "LPTIM2_IN1"},
                Trigger {signal: "LPTIM_IN1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IN2_MUX0", source: "LPTIM2_IN2"},
                Trigger {signal: "LPTIM_IN2_MUX1", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX0", source: "LPTIM2_CH1"},
                Trigger {signal: "LPTIM_IC1_MUX1", source: "COMP1_OUT"},
                Trigger {signal: "LPTIM_IC1_MUX2", source: "COMP2_OUT"},
                Trigger {signal: "LPTIM_IC2_MUX0", source: "LPTIM2_CH2"},
                Trigger {signal: "LPTIM_IC2_MUX1", source: "HSI16_DIV256"},
            ]),
            (r"^STM32WBA5[45].*:SPI1", &[
                Trigger {signal: "SPI_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "SPI_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "SPI_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "SPI_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "SPI_TRG4", source: "EXTI4_TRG"},
                Trigger {signal: "SPI_TRG5", source: "EXTI9_TRG"},
                Trigger {signal: "SPI_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "SPI_TRG7", source: "LPTIM2_CH1"},
                Trigger {signal: "SPI_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "SPI_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "SPI_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "SPI_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA5[45].*:SPI3", &[
                Trigger {signal: "SPI_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "SPI_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "SPI_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "SPI_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "SPI_TRG4", source: "EXTI4_TRG"},
                Trigger {signal: "SPI_TRG5", source: "EXTI8_TRG"},
                Trigger {signal: "SPI_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "SPI_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "SPI_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "SPI_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA5[45].*:USART[12]", &[
                Trigger {signal: "USART_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "USART_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "USART_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "USART_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "USART_TRG4", source: "EXTI6_TRG"},
                Trigger {signal: "USART_TRG5", source: "EXTI9_TRG"},
                Trigger {signal: "USART_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "USART_TRG7", source: "LPTIM2_CH1"},
                Trigger {signal: "USART_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "USART_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "USART_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "USART_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA6[235].*:I2C[124]", &[
                Trigger {signal: "I2C_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "I2C_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "I2C_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "I2C_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "I2C_TRG4", source: "EXTI5_TRG"},
                Trigger {signal: "I2C_TRG5", source: "EXTI9_TRG"},
                Trigger {signal: "I2C_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "I2C_TRG7", source: "LPTIM2_CH1"},
                Trigger {signal: "I2C_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "I2C_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "I2C_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "I2C_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA6[235].*:I2C3", &[
                Trigger {signal: "I2C_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "I2C_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "I2C_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "I2C_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "I2C_TRG4", source: "EXTI5_TRG"},
                Trigger {signal: "I2C_TRG5", source: "EXTI8_TRG"},
                Trigger {signal: "I2C_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "I2C_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "I2C_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "I2C_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "I2C_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA5[45].*:I2C1", &[
                Trigger {signal: "I2C_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "I2C_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "I2C_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "I2C_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "I2C_TRG4", source: "EXTI5_TRG"},
                Trigger {signal: "I2C_TRG5", source: "EXTI9_TRG"},
                Trigger {signal: "I2C_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "I2C_TRG7", source: "LPTIM2_CH1"},
                Trigger {signal: "I2C_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "I2C_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "I2C_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "I2C_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA5[45].*:I2C3", &[
                Trigger {signal: "I2C_TRG0", source: "GPDMA_CH0_TC"},
                Trigger {signal: "I2C_TRG1", source: "GPDMA_CH1_TC"},
                Trigger {signal: "I2C_TRG2", source: "GPDMA_CH2_TC"},
                Trigger {signal: "I2C_TRG3", source: "GPDMA_CH3_TC"},
                Trigger {signal: "I2C_TRG4", source: "EXTI5_TRG"},
                Trigger {signal: "I2C_TRG5", source: "EXTI8_TRG"},
                Trigger {signal: "I2C_TRG6", source: "LPTIM1_CH1"},
                Trigger {signal: "I2C_TRG8", source: "COMP1_OUT"},
                Trigger {signal: "I2C_TRG9", source: "COMP2_OUT"},
                Trigger {signal: "I2C_TRG10", source: "RTC_ALRA_TRG"},
                Trigger {signal: "I2C_TRG11", source: "RTC_WUT_TRG"},
            ]),
            (r"^STM32WBA[56].*:ADC4", &[
                Trigger {signal: "ADC_TRG0", source: "TIM1_TRGO2"},
                Trigger {signal: "ADC_TRG1", source: "TIM1_OC4"},
                Trigger {signal: "ADC_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "ADC_TRG5", source: "LPTIM1_CH1"},
                Trigger {signal: "ADC_TRG7", source: "EXTI15_TRG"},
            ]),
            (r"^STM32WL.*:DAC.*", &[
                Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
                Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
                Trigger {signal: "DAC_CHX_TRG13", source: "LPTIM3_TRGO"},
                Trigger {signal: "DAC_CHX_TRG14", source: "EXTI9_TRG"},
            ]),
            //STM32L4(7|8|9|A)
            (r"^STM32L4(7|8|9|A).*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM16_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                Trigger {signal: "DFSDM1_JTRG9", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG10", source: "EXTI15" },
            ]),
            (r"^STM32L4(7|8|9|A).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2
            ]),
            (r"^STM32L4(7|8|9|A).*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
            //STM32L4(1|2|3|4|5|6)
            (r"^STM32L4(1|2|3|4|5|6).*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM16_OC1" },
                // Trigger {signal: ":DFSDM1_JTRG4", source: "RESERVED" },
                // Trigger {signal: ":DFSDM1_JTRG5", source: "RESERVED" },
                // Trigger {signal: ":DFSDM1_JTRG6", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG8", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG9", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG10", source: "EXTI15" },
                //TODO BREAKS?
            ]),
            (r"^STM32L4(1|2|3|4|5|6).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2
            ]),
            (r"^STM32L4(1|2|3|4|5|6).*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM15 break
            ]),
            (r"^STM32L4(1|2|3|4|5|6).*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM16 break
            ]),
            //STM32H7(4|5)(5|7)
            (r"^STM32H7(4|5)(5|7).*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM16_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                Trigger {signal: "DFSDM1_JTRG9", source: "HRTIM1_ADCTRG1" },
                Trigger {signal: "DFSDM1_JTRG10", source: "HRTIM1_ADCTRG3" },
                // Trigger {signal: ":DFSDM1_JTRG11..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG27", source: "LPTIM2_TRGO" },
                Trigger {signal: "DFSDM1_JTRG28", source: "LPTIM3_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG29..31", source: "RESERVED" },
            ]),
            (r"^STM32H7(4|5)(5|7).*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
            ]),
            (r"^STM32H7(4|5)(5|7).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(4|5)(5|7).*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(4|5)(5|7).*:TIM17.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
            ]),
            (r"^STM32H7(4|5)(5|7).*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
            //STM32F412
            (r"^STM32F412.*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM10_OC1" },
                // Trigger {signal: ":DFSDM1_JTRG4", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG6", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG8", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG9", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG10", source: "EXTI15" },
            ]),
            (r"^STM32F412.*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1 break
            ]),
            (r"^STM32F412.*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break
            ]),
            //STM32F7(7|6)
            (r"^STM32F7(7|6).*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM10_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG9..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG27..31", source: "RESERVED" },
            ]),
            (r"^STM32F7(7|6).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2
            ]),
            (r"^STM32F7(7|6).*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
            // STM32F4(1|2)3
            (r"^STM32F4(1|2)3.*:DFSDM1.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM3_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM10_OC1" },
                // Trigger {signal: ":DFSDM1_JTRG4", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO2" },
                // Trigger {signal: ":DFSDM1_JTRG6", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO1" },
                // Trigger {signal: ":DFSDM1_JTRG8", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG9", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG10", source: "EXTI15" },
            ]),
            (r"^STM32F4(1|2)3.*:DFSDM2.*", &[
                Trigger {signal: "DFSDM2_JTRG0", source: "TIM1_TRGO3" },
                Trigger {signal: "DFSDM2_JTRG1", source: "TIM3_TRGO3" },
                Trigger {signal: "DFSDM2_JTRG2", source: "TIM8_TRGO4" },
                Trigger {signal: "DFSDM2_JTRG3", source: "TIM10_OC1" },
                Trigger {signal: "DFSDM2_JTRG4", source: "TIM2_TRGO2" },
                Trigger {signal: "DFSDM2_JTRG5", source: "TIM4_TRGO4" },
                Trigger {signal: "DFSDM2_JTRG6", source: "TIM11_OC1" },
                Trigger {signal: "DFSDM2_JTRG7", source: "TIM6_TRGO2" },
                Trigger {signal: "DFSDM2_JTRG8", source: "TIM7_TRGO2" },
                Trigger {signal: "DFSDM2_JTRG9", source: "EXTI11" },
                Trigger {signal: "DFSDM2_JTRG10", source: "EXTI15" },
            ]),
            (r"^STM32F4(1|2)3.*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1 break
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM2_BREAK0"},// dfsdm_break[0]  TIM1 break
            ]),
            (r"^STM32F4(1|2)3.*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM2_BREAK2"},// dfsdm_break[2]  TIM8 break
            ]),
            // STM32L4(P|Q|R|S)
            (r"^STM32L4(P|Q|R|S).*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM16_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG9..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" }, //Corrected, TRM says "LTIMER1"
                // Trigger {signal: ":DFSDM1_JTRG27..31", source: "RESERVED" },
            ]),
            (r"^STM32L4(P|Q|R|S).*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
            ]),
            (r"^STM32L4(P|Q|R|S).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32L4(P|Q|R|S).*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32L4(P|Q|R|S).*:TIM17.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
            ]),
            (r"^STM32L4(P|Q|R|S).*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
            //STM32H7(42|43|53|50)
            (r"^STM32H7(42|43|53|50).*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM16_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                Trigger {signal: "DFSDM1_JTRG9", source: "HRTIM1_ADCTRG1" },
                Trigger {signal: "DFSDM1_JTRG10", source: "HRTIM1_ADCTRG3" },
                // Trigger {signal: ":DFSDM1_JTRG11..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG27", source: "LPTIM2_TRGO" },
                Trigger {signal: "DFSDM1_JTRG28", source: "LPTIM3_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG29..31", source: "RESERVED" },
            ]),
            (r"^STM32H7(42|43|53|50).*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
            ]),
            (r"^STM32H7(42|43|53|50).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(42|43|53|50).*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(42|43|53|50).*:TIM17.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
            ]),
            (r"^STM32H7(42|43|53|50).*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
            //STM32MP1(5(1|3|7)|3)
            (r"^STM32MP1(5(1|3|7)|3).*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM16_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG9..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG27", source: "LPTIM2_TRGO" },
                Trigger {signal: "DFSDM1_JTRG28", source: "LPTIM3_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG29..31", source: "RESERVED" },
            ]),
            (r"^STM32MP1(5(1|3|7)|3).*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
            ]),
            (r"^STM32MP1(5(1|3|7)|3).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32MP1(5(1|3|7)|3).*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32MP1(5(1|3|7)|3).*:TIM17.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
            ]),
            (r"^STM32MP1(5(1|3|7)|3).*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
            // STM32H7(A|B)3
            (r"^STM32H7(A|B)3.*:DFSDM1.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM16_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG9..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG27", source: "LPTIM2_TRGO" },
                Trigger {signal: "DFSDM1_JTRG28", source: "LPTIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG29", source: "COMP1_OUT" },
                Trigger {signal: "DFSDM1_JTRG30", source: "COMP2_OUT" },
                // Trigger {signal: ":DFSDM1_JTRG31", source: "RESERVED" },
            ]),
            (r"^STM32H7(A|B)3.*:DFSDM2.*", &[
                // Trigger {signal: ":DFSDM2_JTRG0..23", source: "RESERVED" },
                Trigger {signal: "DFSDM2_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM2_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM2_JTRG26", source: "LPTIM1_TRGO" },
                Trigger {signal: "DFSDM2_JTRG27", source: "LPTIM2_TRGO" },
                Trigger {signal: "DFSDM2_JTRG28", source: "LPTIM3_TRGO" },
                Trigger {signal: "DFSDM2_JTRG29", source: "COMP1_OUT" },
                Trigger {signal: "DFSDM2_JTRG30", source: "COMP2_OUT" },
                // Trigger {signal: ":DFSDM2_JTRG31", source: "RESERVED" },
            ]),
            (r"^STM32H7(A|B)3.*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
            ]),
            (r"^STM32H7(A|B)3.*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(A|B)3.*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(A|B)3.*:LPTIM3.*", &[
                // TODO LPTIM3_ETR doesn't exist as a source yet, so it crashes the buildscript.
                // Trigger {signal: "LPTIM3_ETR", source: "DFSDM2_BREAK0"},// dfsdm_break[0]  LPTIM3_ETR
            ]),
            // STM32H7(23|33|25|35|30)
            (r"^STM32H7(23|33|25|35|30).*:DFSDM1.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG4", source: "TIM3_TRGO" },
                Trigger {signal: "DFSDM1_JTRG5", source: "TIM4_TRGO" },
                Trigger {signal: "DFSDM1_JTRG6", source: "TIM16_OC1" },
                Trigger {signal: "DFSDM1_JTRG7", source: "TIM6_TRGO" },
                Trigger {signal: "DFSDM1_JTRG8", source: "TIM7_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG9..10", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG11", source: "TIM23_TRGO" },
                Trigger {signal: "DFSDM1_JTRG12", source: "TIM24_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG13..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG27", source: "LPTIM2_TRGO" },
                Trigger {signal: "DFSDM1_JTRG28", source: "LPTIM3_TRGO" },
                // Trigger {signal: "DFSDM1_JTRG29", source: "RESERVED" },
                // Trigger {signal: "DFSDM1_JTRG30", source: "RESERVED" },
                // Trigger {signal: ":DFSDM1_JTRG31", source: "RESERVED" },
            ]),
            (r"^STM32H7(23|33|25|35|30).*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
            ]),
            (r"^STM32H7(23|33|25|35|30).*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(23|33|25|35|30).*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32H7(23|33|25|35|30).*:TIM17.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
            ]),
            (r"^STM32H7(23|33|25|35|30).*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
            // STM32L5
            (r"^STM32L5.*:DFSDM.*", &[
                Trigger {signal: "DFSDM1_JTRG0", source: "TIM1_TRGO" },
                Trigger {signal: "DFSDM1_JTRG1", source: "TIM1_TRGO2" },
                Trigger {signal: "DFSDM1_JTRG2", source: "TIM8_TRGO" },
                Trigger {signal: "DFSDM1_JTRG3", source: "TIM8_TRGO2" },
                // Trigger {signal: ":DFSDM1_JTRG9..23", source: "RESERVED" },
                Trigger {signal: "DFSDM1_JTRG24", source: "EXTI11" },
                Trigger {signal: "DFSDM1_JTRG25", source: "EXTI15" },
                Trigger {signal: "DFSDM1_JTRG26", source: "LPTIM1_TRGO" },
                // Trigger {signal: ":DFSDM1_JTRG27..31", source: "RESERVED" },
            ]),
            (r"^STM32L5.*:TIM15.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
            ]),
            (r"^STM32L5.*:TIM1.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK0"},// dfsdm_break[0]  TIM1/TIM15 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32L5.*:TIM16.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK1"},// dfsdm_break[1]  TIM1 break2/TIM16 break
            ]),
            (r"^STM32L5.*:TIM17.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
            ]),
            (r"^STM32L5.*:TIM8.*", &[
                Trigger {signal: "TIMX_BRK_IN1", source: "DFSDM1_BREAK2"},// dfsdm_break[2]  TIM8 break / TIM17 break
                Trigger {signal: "TIMX_BRK_IN2", source: "DFSDM1_BREAK3"},// dfsdm_break[3]  TIM8 break2
            ]),
        ];

        let trigger_expr = Regex::new(r"(?m)(.+?)(\d+)").unwrap();

        for (expr, triggers) in PERIPHERAL_TRIGGER_RULES {
            let mut trigger_sets: HashMap<String, HashSet<&str>> = HashMap::new();

            for trigger in *triggers {
                let matches = trigger_expr.captures(trigger.signal).unwrap();
                let trigger_set = trigger_sets.entry((&matches[1]).to_string()).or_insert(HashSet::new());

                if !trigger_set.insert(trigger.source) || trigger.source != trigger.source.to_uppercase() {
                    panic!(
                        "trigger: failed to validate rules for expr {} (source: {})",
                        *expr, trigger.source
                    );
                }
            }
        }

        Self {
            map: new_regex_map(PERIPHERAL_TRIGGER_RULES.iter().map(|(k, v)| (k, v.to_vec()))),
        }
    }

    /// Get the stop mode limit for a peripheral based on the MCU and peripheral name.
    /// Determines the lowest possible stop mode when a peripheral is enabled.
    ///
    /// Parameters:
    /// - mcu_name: the full name of the MCU (e.g., "STM32WB55RG")
    /// - peripheral: the name of the peripheral (e.g., "USART1")
    pub fn peripheral_trigger_info(&self, mcu_name: &str, peripheral: &str) -> Option<&[Trigger]> {
        self.map.get(&format!("{mcu_name}:{peripheral}")).next().map(|v| &**v)
    }
}
