use crate::util::RegexMap;

pub struct Trigger {
    pub signal: &'static str,
    pub source: &'static str,
}

// /// Trigger selection for STM32F0.
// #[cfg(stm32f0)]
// #[derive(Debug, Copy, Clone, Eq, PartialEq)]
// #[cfg_attr(feature = "defmt", derive(defmt::Format))]
// pub enum TriggerSel {
//     Tim6 = 0,
//     Tim3 = 1,
//     Tim7 = 2,
//     Tim15 = 3,
//     Tim2 = 4,
//     Exti9 = 6,
//     Software = 7,
// }
//

/// Get the stop mode limit for a peripheral based on the MCU and peripheral name.
/// Determines the lowest possible stop mode when a peripheral is enabled.
///
/// Parameters:
/// - mcu_name: the full name of the MCU (e.g., "STM32WB55RG")
/// - peripheral: the name of the peripheral (e.g., "USART1")
pub(crate) fn peripheral_trigger_info(mcu_name: &str, peripheral: &str) -> Option<&'static [Trigger]> {
    /// Regexmap where the key is mcu_name:peripheral and the value is the trigger list.
    #[rustfmt::skip]
    static PERIPHERAL_TRIGGER_RULES: RegexMap<&'static [Trigger]> = RegexMap::new(&[
        (r"^STM32F0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F100.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F101.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F103.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F105.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F107.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F1.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F410.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32L4(5|6).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM5_TRGO"},
        ]),
        (r"^STM32(F2|F4|F7|L4).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM5_TRGO"},
        ]),
        (r"^STM32F3(01|02|18).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F3(03|28|58|98).*:DAC1", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"}, // defaults to TIM8 but can be remapped to TIM3 with DAC_TRIG_RMP in SYSCFG_CFGR1
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F3(03|28|58|98).*:DAC2", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F37(3|8).*:DAC1", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F37(3|8).*:DAC2", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM18_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F334.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "HRTIM_DAC_TRG1"}, // Can be remapped to HRTIM_DACTRG1 using DAC1_TRIG3_RMP in SYSCFG_CFGR3.
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "HRTIM_DAC_TRG2"}, // Requires DAC_TRIG5_RMP set in SYSCFG_CFGR3.
        ]),
        (r"^STM32L0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM3CH3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM21_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32L1.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM9_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32H7(2|3).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG14", source: "TIM23_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "TIM24_TRGO"},
        ]),
        (r"^STM32H7(A|B).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG14", source: "LPTIM3_TRGO"},
        ]),
        (r"^STM32H7.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32(U5|U3).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32(L4|L5).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32H503.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),        
        (r"^STM32H5(6|7).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32H5.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32G0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32U0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG14", source: "EXTI9_TRG"},
        ]),
        (r"^STM32G4.*:DAC(1|4)", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
            Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
            Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
            Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
        ]),
        (r"^STM32G4.*:DAC2", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
            Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
            Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
            Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
        ]),
        (r"^STM32G4.*:DAC3", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG3"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
            Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
            Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
            Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
        ]),
        (r"^STM32WL.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "LPTIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG14", source: "EXTI9_TRG"},
        ]),
    ]);

    PERIPHERAL_TRIGGER_RULES
        .get(&format!("{mcu_name}:{peripheral}"))
        .map(|v| &**v)
}
