use std::collections::{HashMap, HashSet};
use std::sync::atomic::{AtomicBool, Ordering};

use regex::Regex;

use crate::util::RegexMap;

pub struct Trigger {
    pub signal: &'static str,
    pub source: &'static str,
}

/// Get the stop mode limit for a peripheral based on the MCU and peripheral name.
/// Determines the lowest possible stop mode when a peripheral is enabled.
///
/// Parameters:
/// - mcu_name: the full name of the MCU (e.g., "STM32WB55RG")
/// - peripheral: the name of the peripheral (e.g., "USART1")
pub(crate) fn peripheral_trigger_info(mcu_name: &str, peripheral: &str) -> Option<&'static [Trigger]> {
    /// Regexmap where the key is mcu_name:peripheral and the value is the trigger list.
    #[rustfmt::skip]
    static PERIPHERAL_TRIGGER_RULES: RegexMap<&'static [Trigger]> = RegexMap::new(&[
        (r"^STM32F0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F100.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F101.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F103.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F105.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F107.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F1.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F410.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F4.*:ADC.*", &[
            Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_CH1" },
            Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CH2" },
            Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CH3" },
            Trigger {signal: "ADC_EXT_TRG3", source: "TIM2_CH2" },
            Trigger {signal: "ADC_EXT_TRG4", source: "TIM2_CH3" },
            Trigger {signal: "ADC_EXT_TRG5", source: "TIM2_CH4" },
            Trigger {signal: "ADC_EXT_TRG6", source: "TIM2_TRGO" },
            Trigger {signal: "ADC_EXT_TRG7", source: "TIM3_CH1" },
            Trigger {signal: "ADC_EXT_TRG8", source: "TIM3_TRGO" },
            Trigger {signal: "ADC_EXT_TRG9", source: "TIM4_CH4" },
            Trigger {signal: "ADC_EXT_TRG10", source: "TIM5_CH1" },
            Trigger {signal: "ADC_EXT_TRG11", source: "TIM5_CH2" },
            Trigger {signal: "ADC_EXT_TRG12", source: "TIM5_CH3" },
            Trigger {signal: "ADC_EXT_TRG13", source: "TIM8_CH1" },
            Trigger {signal: "ADC_EXT_TRG14", source: "TIM8_TRGO" },
            Trigger {signal: "ADC_EXT_TRG15", source: "EXTI11_TRG" },
            Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_CH4" },
            Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_CH1" },
            Trigger {signal: "ADC_JEXT_TRG3", source: "TIM2_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG4", source: "TIM3_CH2" },
            Trigger {signal: "ADC_JEXT_TRG5", source: "TIM3_CH4" },
            Trigger {signal: "ADC_JEXT_TRG6", source: "TIM4_CH1" },
            Trigger {signal: "ADC_JEXT_TRG7", source: "TIM4_CH2" },
            Trigger {signal: "ADC_JEXT_TRG8", source: "TIM4_CH3" },
            Trigger {signal: "ADC_JEXT_TRG9", source: "TIM4_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG10", source: "TIM5_CH4" },
            Trigger {signal: "ADC_JEXT_TRG11", source: "TIM5_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG12", source: "TIM8_CH2" },
            Trigger {signal: "ADC_JEXT_TRG13", source: "TIM8_CH3" },
            Trigger {signal: "ADC_JEXT_TRG14", source: "TIM8_CH4" },
            Trigger {signal: "ADC_JEXT_TRG15", source: "EXTI15_TRG" },
        ]),
        (r"^STM32L4(5|6).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32(F2|F4|F7|L4).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F3(01|02|18).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F3(03|28|58|98).*:DAC1", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"}, // defaults to TIM8 but can be remapped to TIM3 with DAC_TRIG_RMP in SYSCFG_CFGR1
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F3(03|28|58|98).*:DAC2", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F37(3|8).*:DAC1", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F37(3|8).*:DAC2", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM18_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "EXTI9_TRG"},
        ]),
        (r"^STM32F334.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "HRTIM_DAC_TRG1"}, // Can be remapped to HRTIM_DACTRG1 using DAC1_TRIG3_RMP in SYSCFG_CFGR3.
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "HRTIM_DAC_TRG2"}, // Requires DAC_TRIG5_RMP set in SYSCFG_CFGR3.
        ]),
        (r"^STM32L0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM3CH3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM21_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32L1.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG0", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM9_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
        ]),
        (r"^STM32H7(2|3).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG14", source: "TIM23_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "TIM24_TRGO"},
        ]),
        (r"^STM32H7(A|B).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG14", source: "LPTIM3_TRGO"},
        ]),
        (r"^STM32H7.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32(U5|U3).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32(L4|L5).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32H503.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),        
        (r"^STM32H5(6|7).*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM5_TRGO"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32H5.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32G0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "EXTI9_TRG"},
        ]),
        (r"^STM32U0.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG14", source: "EXTI9_TRG"},
        ]),
        (r"^STM32G4.*:ADC(1|2)", &[
            Trigger {signal: "ADC_EXT_TRG0", source: "TIM1_CC1"},
            Trigger {signal: "ADC_EXT_TRG1", source: "TIM1_CC2"},
            Trigger {signal: "ADC_EXT_TRG2", source: "TIM1_CC3"},
            Trigger {signal: "ADC_EXT_TRG3", source: "TIM2_CC2"},
            Trigger {signal: "ADC_EXT_TRG4", source: "TIM3_TRGO"},
            Trigger {signal: "ADC_EXT_TRG5", source: "TIM4_CC4"},
            Trigger {signal: "ADC_EXT_TRG6", source: "EXTI11_TRG"},
            Trigger {signal: "ADC_EXT_TRG7", source: "TIM8_TRGO"},
            Trigger {signal: "ADC_EXT_TRG8", source: "TIM8_TRGO2"},
            Trigger {signal: "ADC_EXT_TRG9", source: "TIM1_TRGO"},
            Trigger {signal: "ADC_EXT_TRG10", source: "TIM1_TRGO2"},
            Trigger {signal: "ADC_EXT_TRG11", source: "TIM2_TRGO"},
            Trigger {signal: "ADC_EXT_TRG12", source: "TIM4_TRGO"},
            Trigger {signal: "ADC_EXT_TRG13", source: "TIM6_TRGO"},
            Trigger {signal: "ADC_EXT_TRG14", source: "TIM15_TRGO"},
            Trigger {signal: "ADC_EXT_TRG15", source: "TIM3_CC4"},
            Trigger {signal: "ADC_EXT_TRG16", source: "TIM20_TRGO"},
            Trigger {signal: "ADC_EXT_TRG17", source: "TIM20_TRGO2"},
            Trigger {signal: "ADC_EXT_TRG18", source: "TIM20_CC1"},
            Trigger {signal: "ADC_EXT_TRG19", source: "TIM20_CC2"},
            Trigger {signal: "ADC_EXT_TRG20", source: "TIM20_CC3"},
            Trigger {signal: "ADC_EXT_TRG21", source: "HRTIM_ADC_TRG1"},
            Trigger {signal: "ADC_EXT_TRG22", source: "HRTIM_ADC_TRG3"},
            Trigger {signal: "ADC_EXT_TRG23", source: "HRTIM_ADC_TRG5"},
            Trigger {signal: "ADC_EXT_TRG24", source: "HRTIM_ADC_TRG6"},
            Trigger {signal: "ADC_EXT_TRG25", source: "HRTIM_ADC_TRG7"},
            Trigger {signal: "ADC_EXT_TRG26", source: "HRTIM_ADC_TRG8"},
            Trigger {signal: "ADC_EXT_TRG27", source: "HRTIM_ADC_TRG9"},
            Trigger {signal: "ADC_EXT_TRG28", source: "HRTIM_ADC_TRG10"},
            Trigger {signal: "ADC_EXT_TRG29", source: "LPTIMOUT"},
            Trigger {signal: "ADC_EXT_TRG30", source: "TIM7_TRGO"},
            Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CC4" },
            Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG3", source: "TIM2_CC1" },
            Trigger {signal: "ADC_JEXT_TRG4", source: "TIM3_CC4" },
            Trigger {signal: "ADC_JEXT_TRG5", source: "TIM4_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG6", source: "EXTI15_TRG" },
            Trigger {signal: "ADC_JEXT_TRG7", source: "TIM8_CC4" },
            Trigger {signal: "ADC_JEXT_TRG8", source: "TIM1_TRGO2" },
            Trigger {signal: "ADC_JEXT_TRG9", source: "TIM8_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG10", source: "TIM8_TRGO2" },
            Trigger {signal: "ADC_JEXT_TRG11", source: "TIM3_CC3" },
            Trigger {signal: "ADC_JEXT_TRG12", source: "TIM3_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG13", source: "TIM3_CC1" },
            Trigger {signal: "ADC_JEXT_TRG14", source: "TIM6_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG15", source: "TIM15_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG16", source: "TIM20_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG17", source: "TIM20_TRGO2" },
            Trigger {signal: "ADC_JEXT_TRG18", source: "TIM20_CC4" },
            Trigger {signal: "ADC_JEXT_TRG19", source: "HRTIM_ADC_TRG2" },
            Trigger {signal: "ADC_JEXT_TRG20", source: "HRTIM_ADC_TRG4" },
            Trigger {signal: "ADC_JEXT_TRG21", source: "HRTIM_ADC_TRG5" },
            Trigger {signal: "ADC_JEXT_TRG22", source: "HRTIM_ADC_TRG6" },
            Trigger {signal: "ADC_JEXT_TRG23", source: "HRTIM_ADC_TRG7" },
            Trigger {signal: "ADC_JEXT_TRG24", source: "HRTIM_ADC_TRG8" },
            Trigger {signal: "ADC_JEXT_TRG25", source: "HRTIM_ADC_TRG9" },
            Trigger {signal: "ADC_JEXT_TRG26", source: "HRTIM_ADC_TRG10" },
            Trigger {signal: "ADC_JEXT_TRG27", source: "TIM16_CC1" },
            Trigger {signal: "ADC_JEXT_TRG29", source: "LPTIMOUT" },
            Trigger {signal: "ADC_JEXT_TRG30", source: "TIM7_TRGO" },
        ]),
        (r"^STM32G4.*:ADC(3|4|5)", &[
            Trigger {signal: "ADC_EXT_TRG0", source:  "TIM3_CC1" }, 
            Trigger {signal: "ADC_EXT_TRG1", source:  "TIM2_CC3" }, 
            Trigger {signal: "ADC_EXT_TRG2", source:  "TIM1_CC3" }, 
            Trigger {signal: "ADC_EXT_TRG3", source:  "TIM8_CC1" }, 
            Trigger {signal: "ADC_EXT_TRG4", source:  "TIM3_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG5", source:  "EXTI2_TRG" },
            Trigger {signal: "ADC_EXT_TRG6", source:  "TIM4_CC1" }, 
            Trigger {signal: "ADC_EXT_TRG7", source:  "TIM8_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG8", source:  "TIM8_TRGO2" }, 
            Trigger {signal: "ADC_EXT_TRG9", source:  "TIM1_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG10", source:  "TIM1_TRGO2" }, 
            Trigger {signal: "ADC_EXT_TRG11", source:  "TIM2_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG12", source:  "TIM4_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG13", source:  "TIM6_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG14", source:  "TIM15_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG15", source:  "TIM2_CC1" }, 
            Trigger {signal: "ADC_EXT_TRG16", source:  "TIM20_TRGO" }, 
            Trigger {signal: "ADC_EXT_TRG17", source:  "TIM20_TRGO2" }, 
            Trigger {signal: "ADC_EXT_TRG18", source:  "TIM20_CC1" }, 
            Trigger {signal: "ADC_EXT_TRG19", source:  "HRTIM_ADC_TRG2" }, 
            Trigger {signal: "ADC_EXT_TRG20", source:  "HRTIM_ADC_TRG4" }, 
            Trigger {signal: "ADC_EXT_TRG21", source:  "HRTIM_ADC_TRG1" }, 
            Trigger {signal: "ADC_EXT_TRG22", source:  "HRTIM_ADC_TRG3" }, 
            Trigger {signal: "ADC_EXT_TRG23", source:  "HRTIM_ADC_TRG5" }, 
            Trigger {signal: "ADC_EXT_TRG24", source:  "HRTIM_ADC_TRG6" }, 
            Trigger {signal: "ADC_EXT_TRG25", source:  "HRTIM_ADC_TRG7" }, 
            Trigger {signal: "ADC_EXT_TRG26", source:  "HRTIM_ADC_TRG8" }, 
            Trigger {signal: "ADC_EXT_TRG27", source:  "HRTIM_ADC_TRG9" }, 
            Trigger {signal: "ADC_EXT_TRG28", source:  "HRTIM_ADC_TRG10" }, 
            Trigger {signal: "ADC_EXT_TRG29", source:  "LPTIMOUT" }, 
            Trigger {signal: "ADC_EXT_TRG30", source:  "TIM7_TRGO" }, 
            Trigger {signal: "ADC_JEXT_TRG0", source: "TIM1_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG1", source: "TIM1_CC4" },
            Trigger {signal: "ADC_JEXT_TRG2", source: "TIM2_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG3", source: "TIM8_CC2" },
            Trigger {signal: "ADC_JEXT_TRG4", source: "TIM4_CC3" },
            Trigger {signal: "ADC_JEXT_TRG5", source: "TIM4_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG6", source: "TIM4_CC4" },
            Trigger {signal: "ADC_JEXT_TRG7", source: "TIM8_CC4" },
            Trigger {signal: "ADC_JEXT_TRG8", source: "TIM1_TRGO2" },
            Trigger {signal: "ADC_JEXT_TRG9", source: "TIM8_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG10", source: "TIM8_TRGO2" },
            Trigger {signal: "ADC_JEXT_TRG11", source: "TIM1_CC3" },
            Trigger {signal: "ADC_JEXT_TRG12", source: "TIM3_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG13", source: "EXTI3_TRG" },
            Trigger {signal: "ADC_JEXT_TRG14", source: "TIM6_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG15", source: "TIM15_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG16", source: "TIM20_TRGO" },
            Trigger {signal: "ADC_JEXT_TRG17", source: "TIM20_TRGO2" },
            Trigger {signal: "ADC_JEXT_TRG18", source: "TIM20_CC2" },
            Trigger {signal: "ADC_JEXT_TRG19", source: "HRTIM_ADC_TRG2" },
            Trigger {signal: "ADC_JEXT_TRG20", source: "HRTIM_ADC_TRG4" },
            Trigger {signal: "ADC_JEXT_TRG21", source: "HRTIM_ADC_TRG5" },
            Trigger {signal: "ADC_JEXT_TRG22", source: "HRTIM_ADC_TRG6" },
            Trigger {signal: "ADC_JEXT_TRG23", source: "HRTIM_ADC_TRG7" },
            Trigger {signal: "ADC_JEXT_TRG24", source: "HRTIM_ADC_TRG8" },
            Trigger {signal: "ADC_JEXT_TRG25", source: "HRTIM_ADC_TRG9" },
            Trigger {signal: "ADC_JEXT_TRG26", source: "HRTIM_ADC_TRG10" },
            Trigger {signal: "ADC_JEXT_TRG27", source: "HRTIM_ADC_TRG1" },
            Trigger {signal: "ADC_JEXT_TRG28", source: "HRTIM_ADC_TRG3" },
            Trigger {signal: "ADC_JEXT_TRG29", source: "LPTIMOUT" },
            Trigger {signal: "ADC_JEXT_TRG30", source: "TIM7_TRGO" },
        ]),
        (r"^STM32G4.*:DAC(1|4)", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG1"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
            Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
            Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
            Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
        ]),
        (r"^STM32G4.*:DAC2", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM8_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG2"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
            Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
            Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
            Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
        ]),
        (r"^STM32G4.*:DAC3", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG15", source: "HRTIM_DAC_TRG3"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM7_TRGO"},
            Trigger {signal: "DAC_CHX_TRG3", source: "TIM15_TRGO"},
            Trigger {signal: "DAC_CHX_TRG4", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG5", source: "TIM4_TRGO"},
            Trigger {signal: "DAC_CHX_TRG6", source: "EXTI9_TRG"},
            Trigger {signal: "DAC_CHX_TRG7", source: "TIM6_TRGO"},
            Trigger {signal: "DAC_CHX_TRG8", source: "TIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG9", source: "HRTIM_DAC_RESET_TRG1"},
            Trigger {signal: "DAC_CHX_TRG10", source: "HRTIM_DAC_RESET_TRG2"},
            Trigger {signal: "DAC_CHX_TRG11", source: "HRTIM_DAC_RESET_TRG3"},
            Trigger {signal: "DAC_CHX_TRG12", source: "HRTIM_DAC_RESET_TRG4"},
            Trigger {signal: "DAC_CHX_TRG13", source: "HRTIM_DAC_RESET_TRG5"},
            Trigger {signal: "DAC_CHX_TRG14", source: "HRTIM_DAC_RESET_TRG6"},
        ]),
        (r"^STM32WL.*:DAC.*", &[
            Trigger {signal: "DAC_CHX_TRG1", source: "TIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG2", source: "TIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG11", source: "LPTIM1_TRGO"},
            Trigger {signal: "DAC_CHX_TRG12", source: "LPTIM2_TRGO"},
            Trigger {signal: "DAC_CHX_TRG13", source: "LPTIM3_TRGO"},
            Trigger {signal: "DAC_CHX_TRG14", source: "EXTI9_TRG"},
        ]),
    ]);

    static PERIPHERAL_TRIGGER_RULES_VALID: AtomicBool = AtomicBool::new(false);

    if !PERIPHERAL_TRIGGER_RULES_VALID.load(Ordering::Acquire) {
        let trigger_expr = Regex::new(r"(?m)(.+?)(\d+)").unwrap();

        for (expr, triggers) in PERIPHERAL_TRIGGER_RULES.get_map() {
            let mut trigger_sets: HashMap<String, HashSet<&str>> = HashMap::new();

            for trigger in *triggers {
                let matches = trigger_expr.captures(trigger.signal).unwrap();
                let trigger_set = trigger_sets.entry((&matches[1]).to_string()).or_insert(HashSet::new());

                if !trigger_set.insert(trigger.source) || trigger.source != trigger.source.to_uppercase() {
                    panic!(
                        "trigger: failed to validate rules for expr {} (source: {})",
                        *expr, trigger.source
                    );
                }
            }
        }

        PERIPHERAL_TRIGGER_RULES_VALID.store(true, Ordering::Release);
    }

    PERIPHERAL_TRIGGER_RULES
        .get(&format!("{mcu_name}:{peripheral}"))
        .map(|v| &**v)
}
